project:
  type: book
  output-dir: ../docs/white-paper
book:
  title: "Git in Statistical Programming"
  author: "Kieran Martin"
  date: "5/22/2025"
  chapters:
    - index.qmd
    - state.qmd
    - Challenges.qmd
    - part: "Recommendations"
      chapters:
        - recommendations.qmd
        - branching-strategies.qmd
    - audittrail.qmd
    - qcintegration.qmd
    - summary.qmd
    - references.qmd
  appendices:
     - tools.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



